### ISSUE TITLE
Exponential support

### ISSUE THREAD

**Issue by steviemo** [Redempt/Crunch#9]
Hey! Is there anywhere to evaluate the following expression using Crunch?
`1e6 + 1e2`
Thanks!

**Comment by steviemo** [comment]
I parsed the exponents to a double before passing to the formula so this isn't a blocker but interested in hearing your thoughts.

**Comment by steviemo** [comment]
Actually parsing `2e7` to double results in `2.0E7` which fails in a formula with the following exception: `java.lang.NumberFormatException: Non-numeric character in input '2.0E7 + 2.0E7 + 2.0E7'`

**Comment by Redempt** [comment]
Crunch uses its own method for parsing doubles, since the built-in one in Java is slow. As of now there's no support for this, though you could do `2^(10*7)` or define a custom function like `exp10(2, 7)`.

I currently don't plan to add support for raw scientific notation, though I would accept a PR for the feature.
